kind: PersistentVolume
apiVersion: v1
metadata:
  name: sqlpad-pv-volume
  labels:
    type: local
spec:
  storageClassName: sqlpad-s3
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sqlpad"
